version: "3.8"
services:
    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini

    # MySQL database service
    db:
        image: mysql:latest
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env    

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/
